### PR TITLE
Finish cucumber tasks with a proper exit code

### PR DESCRIPTION
**Pull request by jordianguela**
After executing the cucumber task I realised that it didn't finish its execution.

I have added a proper exit code

### CODE REVIEW

**Comment by dtinth** [comment]
I think this shouldn't be done on gulp-cucumber, since people may want to do something else after the Cucumber specs finish (e.g. generating test coverage reports).

Instead, you can listen for an `'end'` event from the returned stream.

By the way, it works for me without this code addition. Did you leave anything in the event loop?

**Comment by jordianguela** [comment]
What I mainly did is to setup a project using: https://github.com/mitchbox/generator-react-boilerplate

after that I just created a HelloWorld Component and wanted to tested with gulp-cucumber. However, when running the test task I realised that it didn't finish. I did not modify anything else.

I execute the gulp development/production tasks : that build and start a server basically and then run gulp-cucumber in another shell.

Any ideas on what could it be causing this? (not exiting from the gulp-cucumber task)

Extra info: in the console I do see a log message saying 'Cucumber task' has finished although it remains there, it doesn't returns to the bash, I must to do a Ctrl+C to abort it and return to the bash.

**Comment by jordianguela** [comment]
I have found what is causing the issue: starting a server with the livereload set to "true"

If you set livereload:false and close the browser connection after the test it works.

But I haven't found how to make it work with livereload on

**Comment by dtinth** [comment]
Yeah, these are the most common problem with Node — some library leaving something in the event loop. I solved my issue by creating an ":exit" variant, which ends the process when the task is done.

``` js
gulp.task('test', function() {
  return run()
})

gulp.task('test:exit', function() {
  return run().then(
    ()  => { process.exit(0) },
    (e) => { setTimeout(() => process.exit(1)); throw e }
  )
})
```

**Pull request closed without merging**
